apiVersion: runtime.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: sample
  labels:
    foo: bar
spec:
  function: |
    module.exports = {
        main: function(event, context) {
          return 'Hello World2'
        }
      }
  functionContentType: "plaintext"
  size: "L"
  runtime: "nodejs8"
